name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  linodeToken:
    required: true
    description: 'Linode APIv4 Token'
outputs:
  username:
    description: 'Linode User associated with APIv4 Token'
runs:
  using: 'node12'
  main: 'main.js'
